project:
  type: book
  output-dir: docs

book:
  title: "Modelling of Renewable Energy Systems"
  author: "Javier Elío, Liina Sangolt"
  chapters:
    - index.qmd
    - intro_data_analysis.qmd
    - wind.qmd
    - solar.qmd
    - hydroelectric.qmd
    - hydrogen.qmd

format:
  html:
    embed-resources: true
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
    fig-align: center

editor: visual

bibliography: references.bib
link-citations: true

